# .readthedocs.yml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# For version 2 (latest version), this spec is required
version: 2

# Build documentation in the docs/ directory with Sphinx
sphinx:
  configuration: docs/conf.py

# Optionally build your docs in additional formats such as PDF
# No additional formats
formats: []

# Install python packages needed for our documentation
#   Put all required packages in the requirements.txt file
python:
  version: 3
  install:
    - requirements: requirements.txt
